// Runner-native check catalog. IDs here are RUNNER IDs (TECH-/PERF-/A11Y-/JRN-/INTEL-/CONN-); map them to the master 100-check spec IDs in the Decision Log.
// impact/effort are 1–5 and drive Top-10 ranking and the 90-day roadmap. Scores are rubric "absolute-v0" (not yet peer-calibrated).
const o = (harness, id, name, theme, impact, effort, why, rec, title) => [id, { harness, name, theme, impact, effort, why, rec, title: title || name }];

export const CATALOG = Object.fromEntries([
  // ── H1 Technical source / DNS
  o('h1', 'TECH-01', 'Availability, HTTPS & redirect hygiene', 'Discoverability', 4, 2, 'Slow or chained redirects and non-HTTPS entry points waste crawl budget and ad-click latency.', 'Collapse redirects to a single hop to the canonical HTTPS host and 301 all http/www variants.', 'Redirect chain or HTTPS entry issues'),
  o('h1', 'TECH-02', 'Canonical tag', 'Discoverability', 3, 1, 'Missing or conflicting canonicals let URL variants (parameters, www/non-www) split ranking and tracking.', 'Add a single absolute self-referencing canonical to every indexable page, in server-rendered HTML.', 'Canonical tag missing or inconsistent'),
  o('h1', 'TECH-03', 'robots.txt', 'Discoverability', 4, 1, 'robots.txt governs crawl access for search engines; errors can block revenue pages or leave crawlers without a sitemap pointer.', 'Serve a valid robots.txt that allows commercial pages, blocks cart/checkout/search params, and declares the sitemap.', 'robots.txt gaps'),
  o('h1', 'TECH-04', 'AI/answer-engine crawler policy (robots.txt)', 'Discoverability', 3, 1, 'If answer-engine search bots are disallowed in robots.txt, the brand may be absent from AI answers. Training-bot blocks are a business choice.', 'Decide policy deliberately: allow search/answer bots (e.g. OAI-SearchBot, PerplexityBot) unless there is a reason not to; confirm WAF rules match robots policy.', 'Answer-engine crawlers disallowed'),
  o('h1', 'TECH-05', 'XML sitemap', 'Discoverability', 3, 2, 'A healthy sitemap speeds discovery of product and content URLs.', 'Publish a sitemap index referenced in robots.txt containing only indexable 200 URLs with accurate lastmod.', 'Sitemap missing or unhealthy'),
  o('h1', 'TECH-06', 'Structured data (schema.org)', 'Discoverability', 4, 2, 'Product, Organization and Review schema feed rich results, shopping surfaces and answer engines.', 'Add/repair JSON-LD: Organization+WebSite on home; Product with Offer (price, currency, availability) and AggregateRating on PDPs.', 'Structured data missing or incomplete'),
  o('h1', 'TECH-07', 'Public tag footprint (detected only)', 'Measurement', 4, 2, 'A visible measurement foundation (analytics + ad platform tags) is a prerequisite for optimization. Detection does not prove correct firing.', 'Confirm analytics and ad-platform tags are present, de-duplicated, and consent-aware; validate accuracy in a Connected review.', 'Measurement tag footprint gaps or duplicates'),
  o('h1', 'TECH-08', 'SPF record', 'Email & deliverability', 3, 1, 'SPF protects sender reputation; broken or over-limit SPF hurts inbox placement for email/SMS-driven revenue.', 'Publish one SPF record under 10 DNS lookups ending in ~all or -all.', 'SPF record issues'),
  o('h1', 'TECH-09', 'DMARC policy', 'Email & deliverability', 4, 2, 'Without an enforced DMARC policy, mailbox providers have less basis to trust (and others can spoof) the brand domain.', 'Publish DMARC with rua reporting, move p=none → quarantine → reject once aligned senders are verified.', 'DMARC missing or not enforced'),
  o('h1', 'TECH-10', 'DKIM (common selectors only)', 'Email & deliverability', 2, 1, 'DKIM selectors are arbitrary, so absence of a guessed selector proves nothing.', 'Verify DKIM in ESP settings (Connected review).', 'DKIM'),
  o('h1', 'TECH-11', 'Static vs rendered content parity', 'Discoverability', 4, 4, 'Crawlers and many answer engines read raw HTML. Content that exists only after JavaScript runs may be invisible to them.', 'Server-render (or pre-render) primary copy, product data, reviews and internal links so they exist in the initial HTML.', 'Key content depends on JavaScript'),
  // ── H2 Performance / accessibility
  o('h2', 'PERF-01', 'Mobile Lighthouse performance (median of runs)', 'Speed & UX', 4, 3, 'Slow mobile pages lose paid and organic visitors before the offer is seen.', 'Prioritize LCP image, third-party script weight and render-blocking resources; re-test after each change.', 'Mobile performance score is low'),
  o('h2', 'PERF-02', 'Largest Contentful Paint (lab, mobile)', 'Speed & UX', 4, 3, 'LCP is how fast the main content appears.', 'Preload/resize the hero image, remove render-blocking CSS/JS, reduce TTFB.', 'Slow Largest Contentful Paint'),
  o('h2', 'PERF-03', 'Cumulative Layout Shift (lab, mobile)', 'Speed & UX', 3, 2, 'Layout shift causes mis-taps and perceived jank.', 'Reserve space for images, embeds, banners and app widgets.', 'Layout shift'),
  o('h2', 'PERF-04', 'Total Blocking Time (lab proxy for responsiveness)', 'Speed & UX', 3, 3, 'High blocking time means the page feels frozen after load. Lab TBT is a proxy for INP, not a measurement of it.', 'Defer/lazy-load third-party apps and split long JavaScript tasks.', 'Main-thread blocking'),
  o('h2', 'PERF-05', 'Page weight (mobile)', 'Speed & UX', 2, 2, 'Heavy pages cost data and time on mobile networks.', 'Compress/resize images, use modern formats, remove unused apps and fonts.', 'Heavy page weight'),
  o('h2', 'PERF-06', 'Field Core Web Vitals (CrUX, real users)', 'Speed & UX', 4, 3, 'Field data reflects real users and is what search systems consume.', 'Address the failing field metric first.', 'Field Core Web Vitals failing'),
  o('h2', 'A11Y-01', 'Lighthouse accessibility score (median)', 'Speed & UX', 3, 2, 'Accessibility defects block customers and carry legal exposure.', 'Fix automated accessibility failures first (contrast, labels, names).', 'Accessibility score is low'),
  o('h2', 'A11Y-02', 'axe-core serious/critical violations (mobile render)', 'Speed & UX', 3, 2, 'Serious/critical violations are the highest-impact automatable accessibility defects. Automated tools cover only part of WCAG.', 'Triage axe serious/critical violations by affected node count; add accessibility checks to release QA.', 'Serious accessibility violations'),
  o('h2', 'SEO-01', 'Lighthouse SEO score (median)', 'Discoverability', 2, 1, 'Basic on-page SEO hygiene.', 'Fix failing Lighthouse SEO audits (titles, meta descriptions, link text, tap targets).', 'Basic on-page SEO audits failing'),
  // ── H3 Controlled browser journey
  o('h3', 'JRN-01', 'Product page discovery & load', 'Conversion', 3, 2, 'If a product page cannot be reached cleanly from public links, shoppers and crawlers struggle too.', 'Ensure product pages are linked from the home page and collections with crawlable links.', 'Product page not cleanly reachable'),
  o('h3', 'JRN-02', 'Variant selection clarity', 'Conversion', 4, 2, 'Confusing variant selection is a common mobile conversion leak.', 'Pre-select the best-selling variant, show price/availability changes immediately, label options clearly.', 'Variant selection friction'),
  o('h3', 'JRN-03', 'Mobile above-the-fold PDP (price, add-to-cart, proof)', 'Conversion', 5, 2, 'Shoppers decide fast on mobile; price, primary CTA and proof should be visible without scrolling.', 'Bring price, add-to-cart and review stars into the first mobile viewport; compress gallery height.', 'Above-the-fold PDP gaps on mobile'),
  o('h3', 'JRN-04', 'PDP reassurance: shipping, delivery timing, returns, reviews, secure payment', 'Conversion', 4, 1, 'Unanswered delivery-timing, returns, proof and payment-safety questions create hesitation before add-to-cart.', 'State whichever of shipping cost, delivery estimate, returns/guarantee, review count and secure-payment wording is not yet visible on the product page without interaction.', 'Product-page reassurance gaps'),
  o('h3', 'JRN-05', 'Add-to-cart feedback', 'Conversion', 4, 2, 'Clear confirmation after add-to-cart reduces abandonment and double-adds.', 'Show a cart drawer/toast with confirmation, line item and a clear checkout path.', 'Weak add-to-cart feedback'),
  o('h3', 'JRN-06', 'Cart friction & merchandising', 'Conversion', 4, 2, 'The cart is where intent is highest; friction and missing incentives cost revenue.', 'Add shipping-threshold progress, express pay, easy quantity edits and a relevant cross-sell.', 'Cart friction'),
  o('h3', 'JRN-07', 'Shipping cost clarity before checkout', 'Conversion', 4, 1, 'Surprise shipping costs are a leading abandonment reason.', 'Show shipping cost or threshold on PDP and in cart before checkout.', 'Shipping cost not clear before checkout'),
  o('h3', 'JRN-08', 'Checkout entry (observation only, no order placed)', 'Conversion', 4, 3, 'Forced account creation and missing express options add friction at the final step.', 'Offer guest checkout and express wallets; keep the entry step to a single click.', 'Checkout entry friction'),
  // ── H4 Public Meta/Google intelligence
  o('h4', 'INTEL-01', 'Meta Ad Library: attributable active creative', 'Competitive', 3, 3, 'Public ad creative shows how the brand shows up to prospects and how much it is testing.', 'Expand creative formats and angle testing; refresh long-running creative.', 'Narrow public Meta creative footprint'),
  o('h4', 'INTEL-02', 'Meta creative → offer → destination alignment', 'Competitive', 4, 3, 'Ads that land on generic pages waste attention; destination and offer should match the promise.', 'Send each angle to a dedicated or best-matching landing page/PDP with the same offer language.', 'Ad destinations/offers misaligned'),
  o('h4', 'INTEL-03', 'Google Ads Transparency: public ad footprint', 'Competitive', 3, 3, 'Shows which Google formats the advertiser runs publicly.', 'Review format coverage (search, shopping, video, display) against category norms.', 'Narrow public Google ad footprint'),
  o('h4', 'INTEL-04', 'Brand-query SERP ownership', 'Competitive', 4, 2, 'Competitors bidding on the brand name, or a weak brand SERP, leak branded demand.', 'Defend brand terms (brand campaign, sitelinks, reviews/PR) and monitor conquesting.', 'Brand SERP not fully owned'),
  o('h4', 'INTEL-05', 'Competitor creative/offer/destination capture', 'Competitive', 3, 2, 'Side-by-side competitor angles reveal offer and messaging gaps.', 'Use captured competitor offers/angles to brief creative tests.', 'Competitor capture'),
  // ── Not assessable Outside-In (always unscored; displayed to preserve the boundary)
  ...[
    ['CONN-01', 'Ad spend / budget'], ['CONN-02', 'Targeting and audiences'], ['CONN-03', 'ROAS / CPA / conversion performance'],
    ['CONN-04', 'Campaign & ad set structure'], ['CONN-05', 'Pixel / conversion-tracking accuracy (events, dedup, CAPI)'], ['CONN-06', 'Account-level performance and trends'],
  ].map(([id, n]) => ({ id, n })).map(({ id, n }) => [id, { harness: 'boundary', class: 'connected', name: n, theme: 'Connected', impact: 0, effort: 0, why: '', rec: '', title: n }]),
]);

export const HARNESS_LABELS = {
  h1: 'Technical source & DNS',
  h2: 'Performance & accessibility',
  h3: 'Controlled browser journey',
  h4: 'Public Meta / Google intelligence',
};
